___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

# WELCOME!

Welcome to "***Car Price Prediction Project***". This is the first medium project of ***Machine Learning*** course. In this project you will have the opportunity to apply many algorithms commonly used for regression problems.

Also, you will apply various processes such as pre-processing, ***train-test spilit*** and ***cross validation*** that you will use in algorithm modeling and prediction processes in Python with ***scikit-learn***. 

Before diving into the project, please take a look at the determines and tasks.

- **NOTE:** This project assumes that you already know the basics of coding in Python. You should also be familiar with the theory behind regression algorithms and scikit-learn module as well as Machine Learning before you begin.


# Determines

**Auto Scout** data which using for this project, scraped from the on-line car trading company(https://www.autoscout24.com)in 2019, contains many features of 9 different car models. In this project, you will use the data set which is already preprocessed and prepared for algorithms .

The aim of this project to understand of machine learning algorithms. Therefore, you will not need any EDA process as you will be working on the edited data.

---

In this Senario, you will estimate the prices of cars using regression algorithms.

While starting you should import the necessary modules and load the data given as pkl file. Also you'll need to do a few pre-processing before moving to modelling. After that you will implement ***Linear Regression, Ridge Regression, Lasso Regression,and Elastic-Net algorithms respectively*** (After completion of Unsupervised Learning section, you can also add bagging and boosting algorithms such as ***Random Forest and XG Boost*** this notebook to develop the project). You can measure the success of your models with regression evaluation metrics as well as with cross validation method.

For the better results, you should try to increase the success of your models by performing hyperparameter tuning. Determine feature importances for the model. You can set your model with the most important features for resource saving. You should try to apply this especially in Random Forest and XG Boost algorithms. Unlike the others, you will perform hyperparameter tuning for Random Forest and XG Boost using the ***GridSearchCV*** method. 

Finally You can compare the performances of algorithms, work more on the algorithm have the most successful prediction rate.






# Tasks

#### 1. Import Modules, Load Data and Data Review
#### 2. Data Pre-Processing
#### 3. Implement Linear Regression 
#### 4. Implement Ridge Regression
#### 5. Implement Lasso Regression 
#### 6. Implement Elastic-Net
#### 7. Visually Compare Models Performance In a Graph

## 1. Import Modules, Load Data and Data Review

In [497]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

#%matplotlib inline
#%matplotlib notebook
plt.rcParams["figure.figsize"] = (10,6)
import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")
pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option('display.max_columns', 100)

In [498]:
df = pd.read_csv("final_scout_dummy.csv")

In [499]:
df.shape

(15915, 140)

In [500]:
df.head()

price        km  prev_owner  nr_of_seats  displacement_cc  \
0 15770.000 56013.000       2.000        5.000         1400.000   
1 14500.000 80000.000       1.000        4.000         1800.000   
2 14640.000 83450.000       1.000        4.000         1600.000   
3 14500.000 73000.000       1.000        4.000         1400.000   
4 16790.000 16200.000       1.000        5.000         1400.000   

   co_2_emission  gears   hp_kw  weight_kg  consumption_comb   age  \
0         99.000  7.000  66.000   1220.000             3.800 3.000   
1        129.000  7.000 141.000   1255.000             5.600 2.000   
2         99.000  7.000  85.000   1135.000             3.800 3.000   
3         99.000  6.000  66.000   1195.000             3.800 3.000   
4        109.000  7.000  66.000   1135.000             4.100 3.000   

   make_model_Audi A2  make_model_Audi A3  make_model_Opel Astra  \
0                   0                   0                      0   
1                   0                   0                      0   
2                   0                   0                      0   
3                   0                   0                      0   
4                   0                   0                      0   

   make_model_Opel Corsa  make_model_Opel Insignia  make_model_Renault Clio  \
0                      0                         0                        0   
1                      0                         0                        0   
2                      0                         0                        0   
3                      0                         0                        0   
4                      0                         0                        0   

   make_model_Renault Duster  make_model_Renault Espace  \
0                          0                          0   
1                          0                          0   
2                          0                          0   
3                          0                          0   
4                          0                          0   

   body_type_Convertible  body_type_Coupe  body_type_Off-Road  \
0                      0                0                   0   
1                      0                0                   0   
2                      0                0                   0   
3                      0                0                   0   
4                      0                0                   0   

   body_type_Other  body_type_Sedans  body_type_Station wagon  \
0                0                 1                        0   
1                0                 1                        0   
2                0                 1                        0   
3                0                 1                        0   
4                0                 1                        0   

   body_type_Transporter  body_type_Van  type_Employee's car  type_New  \
0                      0              0                    0         0   
1                      0              0                    0         0   
2                      0              0                    0         0   
3                      0              0                    0         0   
4                      0              0                    0         0   

   type_Pre-registered  type_Used  paint_type_Perl effect  \
0                    0          1                       0   
1                    0          1                       0   
2                    0          1                       0   
3                    0          1                       0   
4                    0          1                       0   

   paint_type_Uni/basic  gearing_type_Manual  gearing_type_Semi-automatic  \
0                     0                    0                            0   
1                     0                    0                            0   
2                     0                    0                            0   
3                     0                  

In [501]:
df.describe()

price         km  prev_owner  nr_of_seats  displacement_cc  \
count 15915.000  15915.000   15915.000    15915.000        15915.000   
mean  18024.381  31970.092       0.947        4.952         1431.335   
std    7381.679  37073.322       0.395        0.477          283.779   
min    4950.000      0.000       0.000        2.000          900.000   
25%   12850.000   2000.000       1.000        5.000         1200.000   
50%   16900.000  20435.000       1.000        5.000         1500.000   
75%   21900.000  46900.000       1.000        5.000         1600.000   
max   74600.000 317000.000       4.000        7.000         2500.000   

       co_2_emission     gears     hp_kw  weight_kg  consumption_comb  \
count      15915.000 15915.000 15915.000  15915.000         15915.000   
mean         117.736     5.939    88.514   1337.276             4.832   
std           17.858     0.707    26.660    199.804             0.925   
min           36.000     5.000    51.000    840.000             3.000   
25%          104.000     5.000    66.000   1165.000             4.050   
50%          117.000     6.000    85.000   1288.000             4.800   
75%          128.000     6.000   103.000   1472.000             5.400   
max          253.000     9.000   294.000   2471.000            10.000   

            age  make_model_Audi A2  make_model_Audi A3  \
count 15915.000           15915.000           15915.000   
mean      1.393               0.000               0.195   
std       1.120               0.008               0.396   
min       0.000               0.000               0.000   
25%       0.000               0.000               0.000   
50%       1.000               0.000               0.000   
75%       2.000               0.000               0.000   
max       3.000               1.000               1.000   

       make_model_Opel Astra  make_model_Opel Corsa  make_model_Opel Insignia  \
count              15915.000              15915.000                 15915.000   
mean                   0.159                  0.139                     0.163   
std                    0.365                  0.346                     0.370   
min                    0.000                  0.000                     0.000   
25%                    0.000                  0.000                     0.000   
50%                    0.000                  0.000                     0.000   
75%                    0.000                  0.000                     0.000   
max                    1.000                  1.000                     1.000   

       make_model_Renault Clio  make_model_Renault Duster  \
count                15915.000                  15915.000   
mean                     0.116                      0.002   
std                      0.320                      0.046   
min                      0.000                      0.000   
25%                      0.000                      0.000   
50%                      0.000                      0.000   
75%                      0.000                      0.000   
max                      1.000                      1.000   

       make_model_Renault Espace  body_type_Convertible  body_type_Coupe  \
count                  15915.000              15915.000        15915.000   
mean                       0.062                  0.001            0.002   
std                        0.242                  0.022            0.040   
min                        0.000                  0.000            0.000   
25%                        0.000                  0.000            0.000   
50%                        0.000                  0.000            0.000   
75%                        0.000                  0.000            0.000   
max                        1.000                  1.000            1.000   

       body_type_Off-Road  body_type_Other  body_type_Sedans  \
count           15915.000        15915.000         15915.000   
mean                0.004            0.018             0.498   
std           

In [502]:
df.duplicated().sum()

1678

In [503]:
df.drop_duplicates(inplace=True)

In [504]:
df.shape

(14237, 140)

In [505]:
df.describe()

price         km  prev_owner  nr_of_seats  displacement_cc  \
count 14237.000  14237.000   14237.000    14237.000        14237.000   
mean  18097.451  32541.738       0.952        4.950         1436.166   
std    7433.337  37086.683       0.380        0.470          285.198   
min    4950.000      0.000       0.000        2.000          900.000   
25%   12950.000   3744.000       1.000        5.000         1200.000   
50%   16950.000  21000.000       1.000        5.000         1500.000   
75%   21900.000  47000.000       1.000        5.000         1600.000   
max   74600.000 317000.000       4.000        7.000         2500.000   

       co_2_emission     gears     hp_kw  weight_kg  consumption_comb  \
count      14237.000 14237.000 14237.000  14237.000         14237.000   
mean         117.712     5.939    88.707   1341.987             4.821   
std           17.732     0.704    26.535    201.563             0.909   
min           36.000     5.000    51.000    840.000             3.000   
25%          104.000     5.000    66.000   1165.000             4.100   
50%          117.000     6.000    85.000   1315.000             4.800   
75%          128.000     6.000   103.000   1487.000             5.400   
max          253.000     9.000   294.000   2471.000            10.000   

            age  make_model_Audi A2  make_model_Audi A3  \
count 14237.000           14237.000           14237.000   
mean      1.418               0.000               0.193   
std       1.108               0.008               0.395   
min       0.000               0.000               0.000   
25%       0.000               0.000               0.000   
50%       1.000               0.000               0.000   
75%       2.000               0.000               0.000   
max       3.000               1.000               1.000   

       make_model_Opel Astra  make_model_Opel Corsa  make_model_Opel Insignia  \
count              14237.000              14237.000                 14237.000   
mean                   0.163                  0.140                     0.169   
std                    0.369                  0.347                     0.375   
min                    0.000                  0.000                     0.000   
25%                    0.000                  0.000                     0.000   
50%                    0.000                  0.000                     0.000   
75%                    0.000                  0.000                     0.000   
max                    1.000                  1.000                     1.000   

       make_model_Renault Clio  make_model_Renault Duster  \
count                14237.000                  14237.000   
mean                     0.105                      0.001   
std                      0.306                      0.036   
min                      0.000                      0.000   
25%                      0.000                      0.000   
50%                      0.000                      0.000   
75%                      0.000                      0.000   
max                      1.000                      1.000   

       make_model_Renault Espace  body_type_Convertible  body_type_Coupe  \
count                  14237.000              14237.000        14237.000   
mean                       0.062                  0.001            0.002   
std                        0.242                  0.024            0.042   
min                        0.000                  0.000            0.000   
25%                        0.000                  0.000            0.000   
50%                        0.000                  0.000            0.000   
75%                        0.000                  0.000            0.000   
max                        1.000                  1.000            1.000   

       body_type_Off-Road  body_type_Other  body_type_Sedans  \
count           14237.000        14237.000         14237.000   
mean                0.003            0.019             0.502   
std           

In [521]:
df_not_dummy = pd.read_csv("final_scout_not_dummy_instr.csv")
df_not_dummy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15909 entries, 0 to 15908
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   make_model           15909 non-null  object 
 1   body_type            15909 non-null  object 
 2   price                15909 non-null  int64  
 3   km                   15909 non-null  float64
 4   Type                 15909 non-null  object 
 5   Fuel                 15909 non-null  object 
 6   Comfort_Convenience  15909 non-null  object 
 7   Entertainment_Media  15909 non-null  object 
 8   Extras               15909 non-null  object 
 9   Safety_Security      15909 non-null  object 
 10  Gears                15909 non-null  float64
 11  age                  15909 non-null  float64
 12  Previous_Owners      15909 non-null  float64
 13  hp_kW                15909 non-null  float64
 14  Inspection_new       15909 non-null  int64  
 15  Paint_Type           15909 non-null 

## 2. Data Pre-Processing

As you know, the data set must be edited before proceeding to the implementation of the model. As the last step before model fitting, you need to spilit the data set as train and test. Then, you should train the model with train data and evaluate the performance of the model on the test data. You can use the train and test data you have created for all algorithms.

You must also drop your target variable, the column you are trying to predict.

You can use many [performance metrics for regression](https://medium.com/analytics-vidhya/evaluation-metrics-for-regression-problems-343c4923d922) to measure the performance of the regression model you train. You can define a function to view different metric results together.

You can also use the [cross validation](https://towardsdatascience.com/cross-validation-explained-evaluating-estimator-performance-e51e5430ff85) method to measure the estimator performance. Cross validation uses different data samples from your test set and calculates the accuracy score for each data sample. You can calculate the final performance of your estimator by averaging these scores.

In [506]:
X = df.drop("price", axis=1)
y = df["price"]

In [507]:
# split the data

from sklearn.model_selection import train_test_split

In [436]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

## 3. Implement Linear Regression

 - Import the modul
 - Fit the model 
 - Predict the test set
 - Determine feature coefficiant
 - Evaluate model performance (use performance metrics for regression and cross_val_score)
 - Compare different evaluation metrics
 
*Note: You can use the [dir()](https://www.geeksforgeeks.org/python-dir-function/) function to see the methods you need.*

In [508]:
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, Lasso, LassoCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [509]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def train_val(y_train, y_train_pred, y_test, y_pred, model_name):
    
    scores = {model_name+"_train": {"R2" : r2_score(y_train, y_train_pred),
    "mae" : mean_absolute_error(y_train, y_train_pred),
    "mse" : mean_squared_error(y_train, y_train_pred),                          
    "rmse" : np.sqrt(mean_squared_error(y_train, y_train_pred))},
    
    model_name+"_test": {"R2" : r2_score(y_test, y_pred),
    "mae" : mean_absolute_error(y_test, y_pred),
    "mse" : mean_squared_error(y_test, y_pred),
    "rmse" : np.sqrt(mean_squared_error(y_test, y_pred))}}
    
    return pd.DataFrame(scores)

NOT: Farklı scaling methodlar denenebilir.

In [510]:
model_linear = LinearRegression()

In [440]:
# Without scaling

model_linear.fit(X_train, y_train)

LinearRegression()

In [441]:
model_linear.intercept_

18128.884017945693

In [442]:
y_test_pred= model_linear.predict(X_test)
y_test_pred

array([15214.46778656, 22079.63771579, 13259.03431997, ...,
       18160.55379564, 11665.99801866, 15992.72936486])

In [443]:
y_train_pred = model_linear.predict(X_train)
y_train_pred

array([12245.80182898, 17864.05249372, 17731.20255147, ...,
       12846.71198936, 14732.51178471, 21443.37106797])

In [445]:
eval_without_scaling = train_val(y_train, y_train_pred, y_test, y_test_pred, "Linear")
eval_without_scaling

Linear_train  Linear_test
R2           0.892        0.891
mae       1692.842     1719.710
mse    5963598.474  5984584.636
rmse      2442.048     2446.341

In [447]:
# With StandartScaler

scaler = StandardScaler()

In [448]:
Xz_train= scaler.fit_transform(X_train)

In [449]:
Xz_test = scaler.transform(X_test)

In [450]:
model_linear.fit(Xz_train, y_train)

LinearRegression()

In [451]:
y_test_pred= model_linear.predict(Xz_test)
y_test_pred

array([15213.61792236, 22081.83468701, 13256.16011346, ...,
       18156.81146125, 11666.80094304, 15989.49729877])

In [452]:
y_train_pred = model_linear.predict(Xz_train)
y_train_pred

array([12243.58864945, 17862.88434878, 17731.7940132 , ...,
       12847.03934655, 14732.14053576, 21446.01194835])

In [453]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Linear_MinMaxScaler")

Linear_MinMaxScaler_train         Linear_MinMaxScaler_test
R2                        0.892        -67933123417163702272.000
mae                    1692.843                1620881283737.442
mse                 5963601.617 3741212729689367961667633152.000
rmse                   2442.049               61165453727487.117

In [511]:
# With MinMaxScaler

scaler = MinMaxScaler()

In [512]:
Xz_train= scaler.fit_transform(X_train)

In [513]:
Xz_test = scaler.transform(X_test)

In [514]:
model_linear.fit(Xz_train, y_train)

LinearRegression()

In [515]:
y_test_pred= model_linear.predict(Xz_test)
y_test_pred

array([15214.46778658, 22079.63771579, 13259.03431997, ...,
       18160.55379564, 11665.99801866, 15992.72936485])

In [516]:
y_train_pred = model_linear.predict(Xz_train)
y_train_pred

array([12245.80182897, 17864.05249371, 17731.20255147, ...,
       12846.71198936, 14732.5117847 , 21443.37106797])

In [517]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Linear_MinMaxScaler")

Linear_MinMaxScaler_train  Linear_MinMaxScaler_test
R2                        0.892                     0.891
mae                    1692.842                  1719.710
mse                 5963598.474               5984584.636
rmse                   2442.048                  2446.341

In [461]:
# With RobustScaler

scaler = RobustScaler()

In [462]:
Xz_train= scaler.fit_transform(X_train)

In [463]:
Xz_test = scaler.transform(X_test)

In [464]:
model_linear.fit(Xz_train, y_train)

LinearRegression()

In [465]:
y_test_pred= model_linear.predict(Xz_test)
y_test_pred

array([15214.46778658, 22079.63771579, 13259.03431997, ...,
       18160.55379564, 11665.99801866, 15992.72936485])

In [466]:
y_train_pred = model_linear.predict(Xz_train)
y_train_pred

array([12245.80182897, 17864.05249371, 17731.20255147, ...,
       12846.71198936, 14732.5117847 , 21443.37106797])

In [467]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Linear_RobustScaler")

Linear_RobustScaler_train  Linear_RobustScaler_test
R2                        0.892                     0.891
mae                    1692.842                  1719.710
mse                 5963598.474               5984584.636
rmse                   2442.048                  2446.341

In [240]:
from sklearn.pipeline import Pipeline

In [241]:
pipe_lm = Pipeline([("scaler", scaler), ("lm", model_linear)])

In [242]:
# Fit the model

pipe_lm.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('lm', LinearRegression())])

In [243]:
pipe_lm["lm"].coef_

array([-1.39864311e+03, -1.41483776e+01, -1.01643382e+01, -3.46056758e+02,
       -4.54064967e+02,  5.13115542e+02,  2.57225832e+03, -2.77318207e+02,
        4.97431808e+02, -1.77887509e+03,  1.76816526e+15,  5.32215591e+02,
       -1.39222552e+03, -1.74804910e+03, -5.00929703e+02, -1.75111279e+03,
       -5.00097486e+02,  7.77251025e+02,  3.33648685e+01, -5.56076615e+00,
       -3.70582874e+00, -7.80874710e+01, -4.28825598e+00,  1.12906232e+02,
       -1.09041597e+02,  2.21254650e+02, -7.16433367e+02, -3.40978870e+02,
       -6.67540015e+02, -1.31417562e+03, -1.28602001e+01,  6.81782114e+01,
       -5.67725533e+02,  3.91486202e+02, -2.54503750e+02, -5.40803714e+01,
       -1.02480309e+02,  4.74902476e+02,  5.25418063e+02,  5.18916769e+01,
        9.84997393e+01,  3.26606088e+02, -9.90084788e+00, -7.91424668e+01,
        7.64905284e+01,  8.12585698e+01, -5.89829496e+01, -4.47975778e+01,
        1.05011252e+02, -1.97806918e+01,  1.01869030e+02, -1.35179482e+01,
        1.26007070e+01,  

In [244]:
pipe_lm["lm"].intercept_

18028.141472172352

In [245]:
y_test_pred = pipe_lm.predict(X_test)
y_test_pred

array([25720.68706711, 18484.85148814, 11949.07274533, ...,
       15540.48541756, 21789.62351411, 18217.25582796])

In [246]:
y_train_pred = pipe_lm.predict(X_train)
y_train_pred

array([17803.95489755,  9170.54019908, 12639.00440379, ...,
       19999.75127759, 37094.04005811, 15668.62087367])

In [247]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Linear")

Linear_train                     Linear_test
R2           0.895       -12034875560661129216.000
mae       1667.271                370296391964.210
mse    5721477.894 654745214377023687758970880.000
rmse      2391.961              25587989650948.035

In [518]:
# cross validation

from sklearn.model_selection import cross_validate, cross_val_score

In [519]:
scores = cross_validate(model_linear, Xz_train, y_train, scoring = ['r2', 'neg_mean_absolute_error','neg_mean_squared_error', \
                                                            'neg_root_mean_squared_error'], cv = 5)

In [520]:
pd.DataFrame(scores, index = range(1,6))

fit_time  score_time                     test_r2  \
1     0.041       0.002                       0.882   
2     0.057       0.001                       0.888   
3     0.050       0.001                       0.891   
4     0.041       0.002 -2865075606915777036288.000   
5     0.036       0.002  -316444391632459464704.000   

   test_neg_mean_absolute_error         test_neg_mean_squared_error  \
1                     -1764.933                        -6561506.349   
2                     -1677.672                        -5648300.604   
3                     -1710.298                        -6343284.199   
4           -12672071069628.664 -160019350300831817094521683968.000   
5            -3128668408489.934  -17940953565936220197686870016.000   

   test_neg_root_mean_squared_error  
1                         -2561.544  
2                         -2376.615  
3                         -2518.588  
4              -400024187144767.312  
5              -133943844822881.734

In [251]:
scores = pd.DataFrame(scores, index=range(1,6))
scores.iloc[:, 2:].mean()

test_r2                                   0.890
test_neg_mean_absolute_error          -1697.219
test_neg_mean_squared_error        -5983675.591
test_neg_root_mean_squared_error      -2444.256
dtype: float64

In [252]:
# with pipeline

scores = cross_validate(pipe_lm, X_train, y_train, scoring = ['r2', 'neg_mean_absolute_error','neg_mean_squared_error', \
                                                            'neg_root_mean_squared_error'], cv = 5)

In [253]:
pd.DataFrame(scores, index = range(1,6))

fit_time  score_time      test_r2  test_neg_mean_absolute_error  \
1     0.094       0.007 -2787824.745                   -262591.316   
2     0.089       0.008        0.887                     -1710.681   
3     0.097       0.005        0.893                     -1637.133   
4     0.084       0.007        0.891                     -1745.323   
5     0.088       0.007        0.892                     -1661.886   

   test_neg_mean_squared_error  test_neg_root_mean_squared_error  
1         -151611572890134.219                     -12313065.130  
2                 -5952031.509                         -2439.679  
3                 -5378761.070                         -2319.216  
4                 -6804762.891                         -2608.594  
5                 -5697157.233                         -2386.872

In [254]:
scores = pd.DataFrame(scores, index=range(1,6))
scores.iloc[1:, 2:].mean()

test_r2                                   0.891
test_neg_mean_absolute_error          -1688.756
test_neg_mean_squared_error        -5958178.176
test_neg_root_mean_squared_error      -2438.590
dtype: float64

In [255]:
print("train RMSE:", 2391.960/df["price"].mean())
print("test RMSE:", 2456.088/df["price"].mean())

train RMSE: 0.1327069182103424
test RMSE: 0.13626476585453076


## 4. Implement Ridge Regression

- Import the modul 
- Do not forget to scale the data or use Normalize parameter as True 
- Fit the model 
- Predict the test set 
- Evaluate model performance (use performance metrics for regression) 
- Tune alpha hiperparameter by using [cross validation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html) and determine the optimal alpha value.
- Fit the model and predict again with the new alpha value. 

In [471]:
from sklearn.linear_model import Ridge

In [472]:
# without normalization

model_ridge = Ridge() # alpha=1

In [473]:
model_ridge.fit(X_train, y_train)

Ridge()

In [474]:
y_test_pred = model_ridge.predict(X_test)
y_test_pred

array([15217.36219923, 22085.12687331, 13218.79591867, ...,
       18223.70301617, 11654.11848547, 15993.18315957])

In [475]:
y_train_pred = model_ridge.predict(X_train)
y_train_pred

array([12271.41238284, 17879.7488381 , 17721.23899163, ...,
       12849.06369586, 14718.66476705, 21391.81187552])

In [476]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Ridge")

Ridge_train  Ridge_test
R2          0.892       0.892
mae      1693.733    1718.321
mse   5968279.807 5960791.848
rmse     2443.006    2441.473

In [477]:
# with normalization

model_ridge = Ridge(normalize=True) # alpha=1

In [478]:
model_ridge.fit(X_train, y_train)

Ridge(normalize=True)

In [479]:
y_test_pred = model_ridge.predict(X_test)
y_test_pred

array([17551.91461825, 20461.96218795, 13313.80935151, ...,
       19714.7800963 , 12468.45287431, 17062.69627546])

In [480]:
y_train_pred = model_ridge.predict(X_train)
y_train_pred

array([12656.52109168, 18505.14308404, 17277.37548645, ...,
       12688.19214455, 13437.10776032, 20581.7425252 ])

In [481]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Ridge")

Ridge_train  Ridge_test
R2          0.822       0.828
mae      2141.884    2153.824
mse   9837048.206 9495219.038
rmse     3136.407    3081.431

In [482]:
# hyperparameter tuning with CV

from sklearn.linear_model import RidgeCV

In [483]:
alpha_space = np.linspace(0.1, 1, 100)
alpha_space

array([0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
       0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818,
       0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
       0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727,
       0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
       0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636,
       0.37272727, 0.38181818, 0.39090909, 0.4       , 0.40909091,
       0.41818182, 0.42727273, 0.43636364, 0.44545455, 0.45454545,
       0.46363636, 0.47272727, 0.48181818, 0.49090909, 0.5       ,
       0.50909091, 0.51818182, 0.52727273, 0.53636364, 0.54545455,
       0.55454545, 0.56363636, 0.57272727, 0.58181818, 0.59090909,
       0.6       , 0.60909091, 0.61818182, 0.62727273, 0.63636364,
       0.64545455, 0.65454545, 0.66363636, 0.67272727, 0.68181818,
       0.69090909, 0.7       , 0.70909091, 0.71818182, 0.72727273,
       0.73636364, 0.74545455, 0.75454545, 0.76363636, 0.77272

In [484]:
ridge_cv_model = RidgeCV(alphas=alpha_space, cv = 10, scoring= "neg_root_mean_squared_error")

In [485]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
       0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818,
       0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
       0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727,
       0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
       0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636,
       0.37272727, 0.381818...
       0.73636364, 0.74545455, 0.75454545, 0.76363636, 0.77272727,
       0.78181818, 0.79090909, 0.8       , 0.80909091, 0.81818182,
       0.82727273, 0.83636364, 0.84545455, 0.85454545, 0.86363636,
       0.87272727, 0.88181818, 0.89090909, 0.9       , 0.90909091,
       0.91818182, 0.92727273, 0.93636364, 0.94545455, 0.95454545,
       0.96363636, 0.97272727, 0.98181818, 0.99090909, 1.        ]),
        cv=10, scoring='neg_root_mean_squared_error')

In [486]:
y_test_pred = ridge_cv_model.predict(X_test)
y_test_pred

array([15215.30762722, 22082.83428507, 13236.16142915, ...,
       18196.15576852, 11659.36882044, 15992.30665673])

In [487]:
y_train_pred = ridge_cv_model.predict(X_train)
y_train_pred

array([12261.32196376, 17873.50068067, 17725.67177445, ...,
       12847.43206252, 14725.90827379, 21417.15836164])

In [488]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "RidgeCV")

RidgeCV_train  RidgeCV_test
R2            0.892         0.892
mae        1693.416      1718.779
mse     5965486.444   5968532.724
rmse       2442.435      2443.058

In [489]:
ridge_cv_model.alpha_

0.5363636363636364

In [295]:
# 10 different alpha between 0.1-1

alpha_space = np.linspace(0.1, 1, 10)
alpha_space

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [296]:
ridge_cv_model = RidgeCV(alphas=alpha_space, cv = 10, scoring= "neg_root_mean_squared_error")

In [297]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]), cv=10,
        scoring='neg_root_mean_squared_error')

In [298]:
y_test_pred = ridge_cv_model.predict(X_test)
y_test_pred

array([25726.26586087, 18471.96541753, 11974.70598846, ...,
       15547.27874742, 21783.50002387, 18187.19608266])

In [299]:
y_train_pred = ridge_cv_model.predict(X_train)
y_train_pred

array([17837.88317475,  9154.27868454, 12645.89146946, ...,
       19986.97849728, 37089.3900333 , 15656.8275203 ])

In [300]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "RidgeCV")

RidgeCV_train  RidgeCV_test
R2            0.895         0.889
mae        1667.209      1727.586
mse     5723508.539   6030171.350
rmse       2392.386      2455.641

In [301]:
ridge_cv_model.alpha_

1.0

In [302]:
# 10 different alpha between 0.1-100

alpha_space = 10**np.linspace(-2, 2, 100)
alpha_space

array([1.00000000e-02, 1.09749877e-02, 1.20450354e-02, 1.32194115e-02,
       1.45082878e-02, 1.59228279e-02, 1.74752840e-02, 1.91791026e-02,
       2.10490414e-02, 2.31012970e-02, 2.53536449e-02, 2.78255940e-02,
       3.05385551e-02, 3.35160265e-02, 3.67837977e-02, 4.03701726e-02,
       4.43062146e-02, 4.86260158e-02, 5.33669923e-02, 5.85702082e-02,
       6.42807312e-02, 7.05480231e-02, 7.74263683e-02, 8.49753436e-02,
       9.32603347e-02, 1.02353102e-01, 1.12332403e-01, 1.23284674e-01,
       1.35304777e-01, 1.48496826e-01, 1.62975083e-01, 1.78864953e-01,
       1.96304065e-01, 2.15443469e-01, 2.36448941e-01, 2.59502421e-01,
       2.84803587e-01, 3.12571585e-01, 3.43046929e-01, 3.76493581e-01,
       4.13201240e-01, 4.53487851e-01, 4.97702356e-01, 5.46227722e-01,
       5.99484250e-01, 6.57933225e-01, 7.22080902e-01, 7.92482898e-01,
       8.69749003e-01, 9.54548457e-01, 1.04761575e+00, 1.14975700e+00,
       1.26185688e+00, 1.38488637e+00, 1.51991108e+00, 1.66810054e+00,
      

In [303]:
ridge_cv_model = RidgeCV(alphas=alpha_space, cv = 10, scoring= "neg_root_mean_squared_error")

In [304]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([1.00000000e-02, 1.09749877e-02, 1.20450354e-02, 1.32194115e-02,
       1.45082878e-02, 1.59228279e-02, 1.74752840e-02, 1.91791026e-02,
       2.10490414e-02, 2.31012970e-02, 2.53536449e-02, 2.78255940e-02,
       3.05385551e-02, 3.35160265e-02, 3.67837977e-02, 4.03701726e-02,
       4.43062146e-02, 4.86260158e-02, 5.33669923e-02, 5.85702082e-02,
       6.42807312e-02, 7.05480231e-0...
       1.17681195e+01, 1.29154967e+01, 1.41747416e+01, 1.55567614e+01,
       1.70735265e+01, 1.87381742e+01, 2.05651231e+01, 2.25701972e+01,
       2.47707636e+01, 2.71858824e+01, 2.98364724e+01, 3.27454916e+01,
       3.59381366e+01, 3.94420606e+01, 4.32876128e+01, 4.75081016e+01,
       5.21400829e+01, 5.72236766e+01, 6.28029144e+01, 6.89261210e+01,
       7.56463328e+01, 8.30217568e+01, 9.11162756e+01, 1.00000000e+02]),
        cv=10, scoring='neg_root_mean_squared_error')

In [305]:
y_test_pred = ridge_cv_model.predict(X_test)
y_test_pred

array([25724.55638381, 18453.81002811, 12013.63986634, ...,
       15550.31046575, 21777.09242871, 18148.30911432])

In [306]:
y_train_pred = ridge_cv_model.predict(X_train)
y_train_pred

array([17883.94542522,  9133.21626176, 12661.57311374, ...,
       19967.14125601, 37079.89715022, 15649.98163055])

In [307]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "RidgeCV")

RidgeCV_train  RidgeCV_test
R2            0.895         0.889
mae        1668.083      1727.808
mse     5729982.252   6033697.691
rmse       2393.738      2456.359

In [308]:
ridge_cv_model.alpha_

2.656087782946687

In [494]:
scores = cross_validate(model_ridge, Xz_train, y_train, scoring = ['r2', 'neg_mean_absolute_error','neg_mean_squared_error', \
                                                            'neg_root_mean_squared_error'], cv = 5)

In [495]:
pd.DataFrame(scores, index = range(1,6))

fit_time  score_time  test_r2  test_neg_mean_absolute_error  \
1     0.027       0.001    0.819                     -2193.963   
2     0.028       0.002    0.821                     -2126.957   
3     0.036       0.002    0.806                     -2193.489   
4     0.024       0.002    0.810                     -2199.004   
5     0.029       0.002    0.834                     -2090.046   

   test_neg_mean_squared_error  test_neg_root_mean_squared_error  
1                -10057868.472                         -3171.414  
2                 -8997746.696                         -2999.624  
3                -11236454.121                         -3352.082  
4                -10639599.973                         -3261.840  
5                 -9394929.359                         -3065.115

In [496]:
scores = pd.DataFrame(scores, index=range(1,6))
scores.iloc[:, 2:].mean()

test_r2                                    0.818
test_neg_mean_absolute_error           -2160.692
test_neg_mean_squared_error        -10065319.724
test_neg_root_mean_squared_error       -3170.015
dtype: float64

## 5. Implement Lasso Regression

- Import the modul 
- Do not forget to scale the data or use Normalize parameter as True(If needed)
- Fit the model 
- Predict the test set 
- Evaluate model performance (use performance metrics for regression) 
- Tune alpha hyperparameter by using [cross validation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html) and determine the optimal alpha value.
- Fit the model and predict again with the new alpha value.
- Compare different evaluation metrics

*Note: To understand the importance of the alpha hyperparameter, you can observe the effects of different alpha values on feature coefficants.*

## 6. Implement Elastic-Net

- Import the modul 
- Do not forget to scale the data or use Normalize parameter as True(If needed)
- Fit the model 
- Predict the test set 
- Evaluate model performance (use performance metrics for regression) 
- Tune alpha hyperparameter by using [GridSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) and determine the optimal alpha value.
- Fit the model and predict again with the new alpha value.
- Compare different evaluation metrics

## 7. Visually Compare Models Performance In a Graph

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___