___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

# WELCOME!

Welcome to "***Car Price Prediction Project***". This is the first medium project of ***Machine Learning*** course. In this project you will have the opportunity to apply many algorithms commonly used for regression problems.

Also, you will apply various processes such as pre-processing, ***train-test spilit*** and ***cross validation*** that you will use in algorithm modeling and prediction processes in Python with ***scikit-learn***. 

Before diving into the project, please take a look at the determines and tasks.

- **NOTE:** This project assumes that you already know the basics of coding in Python. You should also be familiar with the theory behind regression algorithms and scikit-learn module as well as Machine Learning before you begin.


# Determines

**Auto Scout** data which using for this project, scraped from the on-line car trading company(https://www.autoscout24.com)in 2019, contains many features of 9 different car models. In this project, you will use the data set which is already preprocessed and prepared for algorithms .

The aim of this project to understand of machine learning algorithms. Therefore, you will not need any EDA process as you will be working on the edited data.

---

In this Senario, you will estimate the prices of cars using regression algorithms.

While starting you should import the necessary modules and load the data given as pkl file. Also you'll need to do a few pre-processing before moving to modelling. After that you will implement ***Linear Regression, Ridge Regression, Lasso Regression,and Elastic-Net algorithms respectively*** (After completion of Unsupervised Learning section, you can also add bagging and boosting algorithms such as ***Random Forest and XG Boost*** this notebook to develop the project). You can measure the success of your models with regression evaluation metrics as well as with cross validation method.

For the better results, you should try to increase the success of your models by performing hyperparameter tuning. Determine feature importances for the model. You can set your model with the most important features for resource saving. You should try to apply this especially in Random Forest and XG Boost algorithms. Unlike the others, you will perform hyperparameter tuning for Random Forest and XG Boost using the ***GridSearchCV*** method. 

Finally You can compare the performances of algorithms, work more on the algorithm have the most successful prediction rate.






# Tasks

#### 1. Import Modules, Load Data and Data Review
#### 2. Data Pre-Processing
#### 3. Implement Linear Regression 
#### 4. Implement Ridge Regression
#### 5. Implement Lasso Regression 
#### 6. Implement Elastic-Net
#### 7. Visually Compare Models Performance In a Graph

## 1. Import Modules, Load Data and Data Review

In [219]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

#%matplotlib inline
#%matplotlib notebook
plt.rcParams["figure.figsize"] = (10,6)
import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")
pd.set_option('display.float_format', lambda x: '%.3f' % x)
# pd.set_option()  # to show max column number

In [220]:
df = pd.read_csv("final_scout_dummy.csv")

In [221]:
df.shape

(15915, 140)

In [222]:
df.head()

price        km  prev_owner  nr_of_seats  displacement_cc  \
0 15770.000 56013.000       2.000        5.000         1400.000   
1 14500.000 80000.000       1.000        4.000         1800.000   
2 14640.000 83450.000       1.000        4.000         1600.000   
3 14500.000 73000.000       1.000        4.000         1400.000   
4 16790.000 16200.000       1.000        5.000         1400.000   

   co_2_emission  gears   hp_kw  weight_kg  consumption_comb  ...  \
0         99.000  7.000  66.000   1220.000             3.800  ...   
1        129.000  7.000 141.000   1255.000             5.600  ...   
2         99.000  7.000  85.000   1135.000             3.800  ...   
3         99.000  6.000  66.000   1195.000             3.800  ...   
4        109.000  7.000  66.000   1135.000             4.100  ...   

   SS_Lane departure warning system  SS_Night view assist  \
0                                 0                     0   
1                                 0                     0   
2                                 0                     0   
3                                 0                     0   
4                                 0                     0   

   SS_Passenger-side airbag  SS_Power steering  SS_Rear airbag  \
0                         1                  1               0   
1                         1                  1               0   
2                         1                  1               0   
3                         1                  1               0   
4                         1                  1               0   

   SS_Side airbag  SS_Tire pressure monitoring system  SS_Traction control  \
0               1                                   1                    1   
1               1                                   1                    1   
2               1                                   1                    1   
3               1                                   1                    0   
4               1                                   1                    1   

   SS_Traffic sign recognition  SS_Xenon headlights  
0                            0                    1  
1                            0                    1  
2                            0                    0  
3                            0                    0  
4                            0                    1  

[5 rows x 140 columns]

## 2. Data Pre-Processing

As you know, the data set must be edited before proceeding to the implementation of the model. As the last step before model fitting, you need to spilit the data set as train and test. Then, you should train the model with train data and evaluate the performance of the model on the test data. You can use the train and test data you have created for all algorithms.

You must also drop your target variable, the column you are trying to predict.

You can use many [performance metrics for regression](https://medium.com/analytics-vidhya/evaluation-metrics-for-regression-problems-343c4923d922) to measure the performance of the regression model you train. You can define a function to view different metric results together.

You can also use the [cross validation](https://towardsdatascience.com/cross-validation-explained-evaluating-estimator-performance-e51e5430ff85) method to measure the estimator performance. Cross validation uses different data samples from your test set and calculates the accuracy score for each data sample. You can calculate the final performance of your estimator by averaging these scores.

In [223]:
X = df.drop("price", axis=1)
y = df["price"]

In [224]:
# split the data

from sklearn.model_selection import train_test_split

In [225]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## 3. Implement Linear Regression

 - Import the modul
 - Fit the model 
 - Predict the test set
 - Determine feature coefficiant
 - Evaluate model performance (use performance metrics for regression and cross_val_score)
 - Compare different evaluation metrics
 
*Note: You can use the [dir()](https://www.geeksforgeeks.org/python-dir-function/) function to see the methods you need.*

In [226]:
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, Lasso, LassoCV
from sklearn.preprocessing import StandardScaler

In [227]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def train_val(y_train, y_train_pred, y_test, y_pred, model_name):
    
    scores = {model_name+"_train": {"R2" : r2_score(y_train, y_train_pred),
    "mae" : mean_absolute_error(y_train, y_train_pred),
    "mse" : mean_squared_error(y_train, y_train_pred),                          
    "rmse" : np.sqrt(mean_squared_error(y_train, y_train_pred))},
    
    model_name+"_test": {"R2" : r2_score(y_test, y_pred),
    "mae" : mean_absolute_error(y_test, y_pred),
    "mse" : mean_squared_error(y_test, y_pred),
    "rmse" : np.sqrt(mean_squared_error(y_test, y_pred))}}
    
    return pd.DataFrame(scores)

In [228]:
model_linear = LinearRegression()

In [229]:
model_linear.fit(X_train, y_train)

LinearRegression()

In [230]:
y_test_pred= model_linear.predict(X_test)
y_test_pred

array([25721.45792846, 18485.95901709, 11949.30878748, ...,
       15542.30299108, 21790.04246449, 18220.31462091])

In [231]:
y_train_pred = model_linear.predict(X_train)
y_train_pred

array([17804.00851055,  9169.53518778, 12640.17916537, ...,
       20003.10537686, 37093.19591197, 15665.39360873])

In [232]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Linear")

Linear_train  Linear_test
R2           0.895        0.889
mae       1667.240     1727.617
mse    5721473.838  6032370.274
rmse      2391.960     2456.088

In [233]:
scaler = StandardScaler()

In [234]:
Xz_train= scaler.fit_transform(X_train)

In [235]:
Xz_test = scaler.transform(X_test)

In [236]:
model_linear.fit(Xz_train, y_train)

LinearRegression()

In [237]:
y_test_pred= model_linear.predict(Xz_test)
y_test_pred

array([25720.68706711, 18484.85148814, 11949.07274533, ...,
       15540.48541756, 21789.62351411, 18217.25582796])

In [238]:
y_train_pred = model_linear.predict(Xz_train)
y_train_pred

array([17803.95489755,  9170.54019908, 12639.00440379, ...,
       19999.75127759, 37094.04005811, 15668.62087367])

In [239]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Linear")

Linear_train                     Linear_test
R2           0.895       -12034875560661129216.000
mae       1667.271                370296391964.210
mse    5721477.894 654745214377023687758970880.000
rmse      2391.961              25587989650948.035

In [240]:
from sklearn.pipeline import Pipeline

In [241]:
pipe_lm = Pipeline([("scaler", scaler), ("lm", model_linear)])

In [242]:
# Fit the model

pipe_lm.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('lm', LinearRegression())])

In [243]:
pipe_lm["lm"].coef_

array([-1.39864311e+03, -1.41483776e+01, -1.01643382e+01, -3.46056758e+02,
       -4.54064967e+02,  5.13115542e+02,  2.57225832e+03, -2.77318207e+02,
        4.97431808e+02, -1.77887509e+03,  1.76816526e+15,  5.32215591e+02,
       -1.39222552e+03, -1.74804910e+03, -5.00929703e+02, -1.75111279e+03,
       -5.00097486e+02,  7.77251025e+02,  3.33648685e+01, -5.56076615e+00,
       -3.70582874e+00, -7.80874710e+01, -4.28825598e+00,  1.12906232e+02,
       -1.09041597e+02,  2.21254650e+02, -7.16433367e+02, -3.40978870e+02,
       -6.67540015e+02, -1.31417562e+03, -1.28602001e+01,  6.81782114e+01,
       -5.67725533e+02,  3.91486202e+02, -2.54503750e+02, -5.40803714e+01,
       -1.02480309e+02,  4.74902476e+02,  5.25418063e+02,  5.18916769e+01,
        9.84997393e+01,  3.26606088e+02, -9.90084788e+00, -7.91424668e+01,
        7.64905284e+01,  8.12585698e+01, -5.89829496e+01, -4.47975778e+01,
        1.05011252e+02, -1.97806918e+01,  1.01869030e+02, -1.35179482e+01,
        1.26007070e+01,  

In [244]:
pipe_lm["lm"].intercept_

18028.141472172352

In [245]:
y_test_pred = pipe_lm.predict(X_test)
y_test_pred

array([25720.68706711, 18484.85148814, 11949.07274533, ...,
       15540.48541756, 21789.62351411, 18217.25582796])

In [246]:
y_train_pred = pipe_lm.predict(X_train)
y_train_pred

array([17803.95489755,  9170.54019908, 12639.00440379, ...,
       19999.75127759, 37094.04005811, 15668.62087367])

In [247]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Linear")

Linear_train                     Linear_test
R2           0.895       -12034875560661129216.000
mae       1667.271                370296391964.210
mse    5721477.894 654745214377023687758970880.000
rmse      2391.961              25587989650948.035

In [248]:
# cross validation

from sklearn.model_selection import cross_validate, cross_val_score

In [249]:
scores = cross_validate(model_linear, X_train, y_train, scoring = ['r2', 'neg_mean_absolute_error','neg_mean_squared_error', \
                                                            'neg_root_mean_squared_error'], cv = 5)

In [250]:
pd.DataFrame(scores, index = range(1,6))

fit_time  score_time  test_r2  test_neg_mean_absolute_error  \
1     0.070       0.005    0.888                     -1731.275   
2     0.060       0.006    0.887                     -1710.617   
3     0.061       0.004    0.893                     -1637.162   
4     0.049       0.004    0.891                     -1745.330   
5     0.060       0.004    0.892                     -1661.710   

   test_neg_mean_squared_error  test_neg_root_mean_squared_error  
1                 -6085859.410                         -2466.953  
2                 -5951906.355                         -2439.653  
3                 -5379346.108                         -2319.342  
4                 -6804732.478                         -2608.588  
5                 -5696533.603                         -2386.741

In [251]:
scores = pd.DataFrame(scores, index=range(1,6))
scores.iloc[:, 2:].mean()

test_r2                                   0.890
test_neg_mean_absolute_error          -1697.219
test_neg_mean_squared_error        -5983675.591
test_neg_root_mean_squared_error      -2444.256
dtype: float64

In [252]:
# with pipeline

scores = cross_validate(pipe_lm, X_train, y_train, scoring = ['r2', 'neg_mean_absolute_error','neg_mean_squared_error', \
                                                            'neg_root_mean_squared_error'], cv = 5)

In [253]:
pd.DataFrame(scores, index = range(1,6))

fit_time  score_time      test_r2  test_neg_mean_absolute_error  \
1     0.094       0.007 -2787824.745                   -262591.316   
2     0.089       0.008        0.887                     -1710.681   
3     0.097       0.005        0.893                     -1637.133   
4     0.084       0.007        0.891                     -1745.323   
5     0.088       0.007        0.892                     -1661.886   

   test_neg_mean_squared_error  test_neg_root_mean_squared_error  
1         -151611572890134.219                     -12313065.130  
2                 -5952031.509                         -2439.679  
3                 -5378761.070                         -2319.216  
4                 -6804762.891                         -2608.594  
5                 -5697157.233                         -2386.872

In [254]:
scores = pd.DataFrame(scores, index=range(1,6))
scores.iloc[1:, 2:].mean()

test_r2                                   0.891
test_neg_mean_absolute_error          -1688.756
test_neg_mean_squared_error        -5958178.176
test_neg_root_mean_squared_error      -2438.590
dtype: float64

In [255]:
print("train RMSE:", 2391.960/df["price"].mean())
print("test RMSE:", 2456.088/df["price"].mean())

train RMSE: 0.1327069182103424
test RMSE: 0.13626476585453076


## 4. Implement Ridge Regression

- Import the modul 
- Do not forget to scale the data or use Normalize parameter as True 
- Fit the model 
- Predict the test set 
- Evaluate model performance (use performance metrics for regression) 
- Tune alpha hiperparameter by using [cross validation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html) and determine the optimal alpha value.
- Fit the model and predict again with the new alpha value. 

In [257]:
from sklearn.linear_model import Ridge

In [258]:
# without normalization

model_ridge = Ridge() # alpha=1

In [259]:
model_ridge.fit(X_train, y_train)

Ridge()

In [260]:
y_test_pred = model_ridge.predict(X_test)
y_test_pred

array([25726.26586087, 18471.96541753, 11974.70598846, ...,
       15547.27874742, 21783.50002387, 18187.19608266])

In [261]:
y_train_pred = model_ridge.predict(X_train)
y_train_pred

array([17837.88317475,  9154.27868454, 12645.89146946, ...,
       19986.97849728, 37089.3900333 , 15656.8275203 ])

In [262]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Ridge")

Ridge_train  Ridge_test
R2          0.895       0.889
mae      1667.209    1727.586
mse   5723508.539 6030171.350
rmse     2392.386    2455.641

In [263]:
# with normalization

model_ridge = Ridge(normalize=True) # alpha=1

In [264]:
model_ridge.fit(X_train, y_train)

Ridge(normalize=True)

In [265]:
y_test_pred = model_ridge.predict(X_test)
y_test_pred

array([20583.60680338, 17832.6673116 , 13665.42825866, ...,
       16283.70579847, 20997.36093596, 17485.97174397])

In [266]:
y_train_pred = model_ridge.predict(X_train)
y_train_pred

array([17765.5965657 , 10539.79191356, 15029.09232823, ...,
       18264.80277217, 33293.46113329, 17728.14092292])

In [267]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "Ridge")

Ridge_train  Ridge_test
R2          0.823       0.825
mae      2139.109    2143.384
mse   9636471.133 9498398.677
rmse     3104.267    3081.947

In [268]:
# hyperparameter tuning with CV

from sklearn.linear_model import RidgeCV

In [288]:
alpha_space = np.linspace(0.1, 1, 100)
alpha_space

array([0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
       0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818,
       0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
       0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727,
       0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
       0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636,
       0.37272727, 0.38181818, 0.39090909, 0.4       , 0.40909091,
       0.41818182, 0.42727273, 0.43636364, 0.44545455, 0.45454545,
       0.46363636, 0.47272727, 0.48181818, 0.49090909, 0.5       ,
       0.50909091, 0.51818182, 0.52727273, 0.53636364, 0.54545455,
       0.55454545, 0.56363636, 0.57272727, 0.58181818, 0.59090909,
       0.6       , 0.60909091, 0.61818182, 0.62727273, 0.63636364,
       0.64545455, 0.65454545, 0.66363636, 0.67272727, 0.68181818,
       0.69090909, 0.7       , 0.70909091, 0.71818182, 0.72727273,
       0.73636364, 0.74545455, 0.75454545, 0.76363636, 0.77272

In [289]:
ridge_cv_model = RidgeCV(alphas=alpha_space, cv = 10, scoring= "neg_root_mean_squared_error")

In [290]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
       0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818,
       0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
       0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727,
       0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
       0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636,
       0.37272727, 0.381818...
       0.73636364, 0.74545455, 0.75454545, 0.76363636, 0.77272727,
       0.78181818, 0.79090909, 0.8       , 0.80909091, 0.81818182,
       0.82727273, 0.83636364, 0.84545455, 0.85454545, 0.86363636,
       0.87272727, 0.88181818, 0.89090909, 0.9       , 0.90909091,
       0.91818182, 0.92727273, 0.93636364, 0.94545455, 0.95454545,
       0.96363636, 0.97272727, 0.98181818, 0.99090909, 1.        ]),
        cv=10, scoring='neg_root_mean_squared_error')

In [291]:
y_test_pred = ridge_cv_model.predict(X_test)
y_test_pred

array([25726.26586087, 18471.96541753, 11974.70598846, ...,
       15547.27874742, 21783.50002387, 18187.19608266])

In [292]:
y_train_pred = ridge_cv_model.predict(X_train)
y_train_pred

array([17837.88317475,  9154.27868454, 12645.89146946, ...,
       19986.97849728, 37089.3900333 , 15656.8275203 ])

In [293]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "RidgeCV")

RidgeCV_train  RidgeCV_test
R2            0.895         0.889
mae        1667.209      1727.586
mse     5723508.539   6030171.350
rmse       2392.386      2455.641

In [294]:
ridge_cv_model.alpha_

1.0

In [295]:
# 10 different alpha between 0.1-1

alpha_space = np.linspace(0.1, 1, 10)
alpha_space

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [296]:
ridge_cv_model = RidgeCV(alphas=alpha_space, cv = 10, scoring= "neg_root_mean_squared_error")

In [297]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]), cv=10,
        scoring='neg_root_mean_squared_error')

In [298]:
y_test_pred = ridge_cv_model.predict(X_test)
y_test_pred

array([25726.26586087, 18471.96541753, 11974.70598846, ...,
       15547.27874742, 21783.50002387, 18187.19608266])

In [299]:
y_train_pred = ridge_cv_model.predict(X_train)
y_train_pred

array([17837.88317475,  9154.27868454, 12645.89146946, ...,
       19986.97849728, 37089.3900333 , 15656.8275203 ])

In [300]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "RidgeCV")

RidgeCV_train  RidgeCV_test
R2            0.895         0.889
mae        1667.209      1727.586
mse     5723508.539   6030171.350
rmse       2392.386      2455.641

In [301]:
ridge_cv_model.alpha_

1.0

In [302]:
# 10 different alpha between 0.1-100

alpha_space = 10**np.linspace(-2, 2, 100)
alpha_space

array([1.00000000e-02, 1.09749877e-02, 1.20450354e-02, 1.32194115e-02,
       1.45082878e-02, 1.59228279e-02, 1.74752840e-02, 1.91791026e-02,
       2.10490414e-02, 2.31012970e-02, 2.53536449e-02, 2.78255940e-02,
       3.05385551e-02, 3.35160265e-02, 3.67837977e-02, 4.03701726e-02,
       4.43062146e-02, 4.86260158e-02, 5.33669923e-02, 5.85702082e-02,
       6.42807312e-02, 7.05480231e-02, 7.74263683e-02, 8.49753436e-02,
       9.32603347e-02, 1.02353102e-01, 1.12332403e-01, 1.23284674e-01,
       1.35304777e-01, 1.48496826e-01, 1.62975083e-01, 1.78864953e-01,
       1.96304065e-01, 2.15443469e-01, 2.36448941e-01, 2.59502421e-01,
       2.84803587e-01, 3.12571585e-01, 3.43046929e-01, 3.76493581e-01,
       4.13201240e-01, 4.53487851e-01, 4.97702356e-01, 5.46227722e-01,
       5.99484250e-01, 6.57933225e-01, 7.22080902e-01, 7.92482898e-01,
       8.69749003e-01, 9.54548457e-01, 1.04761575e+00, 1.14975700e+00,
       1.26185688e+00, 1.38488637e+00, 1.51991108e+00, 1.66810054e+00,
      

In [303]:
ridge_cv_model = RidgeCV(alphas=alpha_space, cv = 10, scoring= "neg_root_mean_squared_error")

In [304]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([1.00000000e-02, 1.09749877e-02, 1.20450354e-02, 1.32194115e-02,
       1.45082878e-02, 1.59228279e-02, 1.74752840e-02, 1.91791026e-02,
       2.10490414e-02, 2.31012970e-02, 2.53536449e-02, 2.78255940e-02,
       3.05385551e-02, 3.35160265e-02, 3.67837977e-02, 4.03701726e-02,
       4.43062146e-02, 4.86260158e-02, 5.33669923e-02, 5.85702082e-02,
       6.42807312e-02, 7.05480231e-0...
       1.17681195e+01, 1.29154967e+01, 1.41747416e+01, 1.55567614e+01,
       1.70735265e+01, 1.87381742e+01, 2.05651231e+01, 2.25701972e+01,
       2.47707636e+01, 2.71858824e+01, 2.98364724e+01, 3.27454916e+01,
       3.59381366e+01, 3.94420606e+01, 4.32876128e+01, 4.75081016e+01,
       5.21400829e+01, 5.72236766e+01, 6.28029144e+01, 6.89261210e+01,
       7.56463328e+01, 8.30217568e+01, 9.11162756e+01, 1.00000000e+02]),
        cv=10, scoring='neg_root_mean_squared_error')

In [305]:
y_test_pred = ridge_cv_model.predict(X_test)
y_test_pred

array([25724.55638381, 18453.81002811, 12013.63986634, ...,
       15550.31046575, 21777.09242871, 18148.30911432])

In [306]:
y_train_pred = ridge_cv_model.predict(X_train)
y_train_pred

array([17883.94542522,  9133.21626176, 12661.57311374, ...,
       19967.14125601, 37079.89715022, 15649.98163055])

In [307]:
train_val(y_train, y_train_pred, y_test, y_test_pred, "RidgeCV")

RidgeCV_train  RidgeCV_test
R2            0.895         0.889
mae        1668.083      1727.808
mse     5729982.252   6033697.691
rmse       2393.738      2456.359

In [308]:
ridge_cv_model.alpha_

2.656087782946687

## 5. Implement Lasso Regression

- Import the modul 
- Do not forget to scale the data or use Normalize parameter as True(If needed)
- Fit the model 
- Predict the test set 
- Evaluate model performance (use performance metrics for regression) 
- Tune alpha hyperparameter by using [cross validation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html) and determine the optimal alpha value.
- Fit the model and predict again with the new alpha value.
- Compare different evaluation metrics

*Note: To understand the importance of the alpha hyperparameter, you can observe the effects of different alpha values on feature coefficants.*

## 6. Implement Elastic-Net

- Import the modul 
- Do not forget to scale the data or use Normalize parameter as True(If needed)
- Fit the model 
- Predict the test set 
- Evaluate model performance (use performance metrics for regression) 
- Tune alpha hyperparameter by using [GridSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) and determine the optimal alpha value.
- Fit the model and predict again with the new alpha value.
- Compare different evaluation metrics

## 7. Visually Compare Models Performance In a Graph

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___